hydra:
  job:
    chdir: True

process_data:
  raw_data_dir_path: "/absolute/path/to/raw/data/dir"
  processed_data_dir_path: "/absolute/path/to/processed/data/dir"

train_model:
  mlflow_exp_name: "experiment-01"
  data_dir_path: "/absolute/path/to/processed/data/dir"
  no_cuda: true
  no_mps: true
  train_bs: 64
  test_bs: 1000
  lr: 0.01
  gamma: 0.7
  seed: 1111
  epochs: 5
  log_interval: 100
  dry_run: false
  model_checkpoint_interval: 2
  model_checkpoint_dir_path: "/absolute/path/to/model/dir"

batch_infer:
  model_path: "/absolute/path/to/models/model.pt"
  input_data_dir: "/absolute/path/to/data/batch-infer-data-dir"
  use_cuda: false
  use_mps: false
